coverage_service: cobertura_xml
workspace: UhooiPicBook.xcworkspace
xcodeproj: Develop.xcodeproj
scheme: UhooiPicBook
source_directory: UhooiPicBook
output_directory: xml_report
ignore:
  - SourcePackages/*
  - "**/AppDelegate.swift"
  - "**/SceneDelegate.swift"
  - "**/Generated/*"
  - "**/Util/Debug.swift"
  - "**/Extensions/UIKit/*"
  - "**/UIParts/*"
  - "**/Views/*"
  - "**/Routers/*"

