parent_config: https://raw.githubusercontent.com/uhooi/SwiftLint-Config/v1.2.0/uhooi-base-swiftlint-config.yml

included:
  - Shared
  - UhooiPicBook
  - UhooiPicBookStickers
  - UhooiPicBookWidgets
  - UhooiPicBookWidgetsConfigurableIntent
  #- UhooiPicBookTests
  #- UhooiPicBookUITests

excluded:
  - UhooiPicBook/Generated

