name: CI

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
      - Rambafile
  pull_request:
    branches:
      # - !main
      - develop
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
      - Rambafile

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app

jobs:
  build:
    name: Build for ${{ matrix.environment }}
    runs-on: macos-11
    strategy:
      matrix:
        environment: ["develop", "production"]

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # セットアップ
    - uses: ./.github/workflows/templates/setup-ios

    # ビルド
    - name: Xcode build for ${{ matrix.environment }}
      run: make build-${{ matrix.environment }}-debug

    # ビルドログのアップロード
    - name: Upload build log Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: xcodebuild-logs
        path: xcodebuild_build.log
        if-no-files-found: ignore
        retention-days: 14

  test:
    runs-on: macos-11

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # セットアップ
    - uses: ./.github/workflows/templates/setup-ios

    # モックの生成
    - name: Generate mocks with Mockolo
      run: make generate-mocks

    # 単体テストの実行
    - name: Xcode test
      run: make test-develop-debug

    # 結果の表示
    - uses: kishikawakatsumi/xcresulttool@v1
      if: success() || failure()
      with:
        path: TestResults.xcresult

    # 単体テストログのアップロード
    - name: Upload test log Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: xcodebuild-logs
        path: |
          xcodebuild_test.log
        if-no-files-found: ignore
        retention-days: 14

    # コードカバレッジをHTML形式で取得
    - name: Get code coverage for HTML
      run: make get-coverage-html

    # テスト結果とコードカバレッジのアップロード
    - name: Upload test results and code coverage Artifact
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: results
        path: |
          TestResults.xcresult
          html_report/**/*
        if-no-files-found: warn
        retention-days: 14

    # コードカバレッジをCobertura形式で取得
    - name: Get code coverage for Cobertura
      run: make get-coverage-cobertura

    # コードカバレッジをCodecovへアップロード
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./xml_report/cobertura.xml
        fail_ci_if_error: true
        verbose: true

  info:
    runs-on: macos-11

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # 情報の出力
    - uses: ./.github/workflows/templates/output-info

