name: CI

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
      - Rambafile
  pull_request:
    branches:
      # - !main
      - develop
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
      - Rambafile

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app

jobs:
  build:
    name: build for ${{ matrix.environment }}
    runs-on: macos-11
    strategy:
      matrix:
        environment: ["develop", "production"]

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # セットアップ
    - uses: ./.github/workflows/templates/setup-ios

    # ビルド
    - name: Xcode build for ${{ matrix.environment }}
      run: make build-debug-${{ matrix.environment }}

    # ビルドログのアップロード
    - name: Upload build log Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: xcodebuild-logs
        path: |
          *_Build.log
        if-no-files-found: ignore
        retention-days: 14

  test:
    name: test for ${{ matrix.name }}
    runs-on: macos-11
    strategy:
      matrix:
        name: ["develop", "app-module"]

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # セットアップ
    - uses: ./.github/workflows/templates/setup-ios

    # モックの生成
    - name: Generate mocks with Mockolo
      run: make generate-mocks

    # 単体テストの実行
    - name: Xcode test
      run: make test-debug-${{ matrix.name }}

    # テスト結果のアップロード
    - name: Upload test results Artifact
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: test-results
        path: |
          *.xcresult
        if-no-files-found: error
        retention-days: 14

    # 単体テストログのアップロード
    - name: Upload test log Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: xcodebuild-logs
        path: |
          *_Test.log
        if-no-files-found: ignore
        retention-days: 14

  show-test-results:
    runs-on: macos-11
    needs: test

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # テスト結果のダウンロード
    - name: Download test results artifact
      uses: actions/download-artifact@v2
      with:
        name: test-results

    # テスト結果のマージ
    - name: Merge test results
      run: make merge-xcresults

    # テスト結果の表示とアップロード
    - uses: kishikawakatsumi/xcresulttool@v1
      if: success() || failure()
      with:
        path: TestResults.xcresult

  info:
    runs-on: macos-11

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # 情報の出力
    - uses: ./.github/workflows/templates/output-info

