name: CI

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
      - Rambafile
  pull_request:
    branches:
      # - !main
      - develop
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
      - Rambafile

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.app

jobs:
  build:
    runs-on: macos-11

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # セットアップ
    - uses: ./.github/workflows/templates/setup-ios
      with:
        environment: 'develop'

    # ビルド
    - name: Xcode build
      run: make build-debug

    # ビルドログのアップロード
    - name: Upload build log Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: xcodebuild-logs
        path: xcodebuild_build.log
        if-no-files-found: ignore
        retention-days: 14

  test:
    runs-on: macos-11

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # セットアップ
    - uses: ./.github/workflows/templates/setup-ios
      with:
        environment: 'develop'

    # 単体テストの実行
    - name: Xcode test
      run: make test

    # 結果の表示
    - uses: kishikawakatsumi/xcresulttool@v1
      if: success() || failure()
      with:
        path: TestResults.xcresult

    # 単体テストログのアップロード
    - name: Upload test log Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: xcodebuild-logs
        path: |
          xcodebuild_test.log
        if-no-files-found: ignore
        retention-days: 14

    # コードカバレッジをHTML形式で取得
    - name: Get code coverage for HTML
      run: make get-coverage-html

    # テスト結果とコードカバレッジのアップロード
    - name: Upload test results and code coverage Artifact
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: results
        path: |
          TestResults.xcresult
          html_report/**/*
        if-no-files-found: warn
        retention-days: 14

    # コードカバレッジをCobertura形式で取得
    - name: Get code coverage for Cobertura
      run: make get-coverage-cobertura

    # コードカバレッジをCodecovへアップロード
    - name: Upload code coverage to Codecov
      run: make upload-coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  info:
    runs-on: macos-11

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # 情報の出力
    - uses: ./.github/workflows/templates/output-info

